###
GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiR2FsaWggQWRoaSIsImlhdCI6MTY1NzE3NjQ0MCwiZXhwIjoxNjU3MTc2NDU1fQ.10FIez3HD4_h5ZiuVQFWYct-OnDFM8xFC5eAUAcBqf4

###
POST http://localhost:3001/users
Content-Type: application/json

{
    "username" : "Galih Adhi",
    "password" : "123",
    "confirmationPass" : "123"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username" : "Galih Adhi",
    "password" : "123"
}

###
POST http://localhost:3001/token

###
DELETE http://localhost:3001/logout
Content-Type: application/json

{
    "username" : "Galih Adhi",
    "password" : "123"
}