###
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJOYW1lIjoiR2FsaWggQWRoaSIsInVzZXJfbGluayI6InVzZXIxMDIzIiwiaWF0IjoxNjU3Mjc1MzQxLCJleHAiOjE2NTcyNzUzNTZ9.VpDbPSAIW4SmS2S_5rS-pyyaDOB--K95UdqpfjG3BAM
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username" : "ropik",
    "password" : "123",
    "confirmationPass" : "123"

}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username" : "ropik",
    "password" : "123"
}

###
GET http://localhost:3001/api/token

###
DELETE http://localhost:3001/logout
Content-Type: application/json

{
    "username" : "Galih Adhi",
    "password" : "123"
}


###
POST http://localhost:3001/api/send/message/test~483
Content-Type: application/json

{
    "from" : "galih",
    "to" : "test",
    "message": "ayo jhon"
}

###
GET http://localhost:3001/api/get/message/ropik~68!
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJ1c2VybmFtZSI6InJvcGlrIiwidXNlcl9saW5rIjoicm9waWt-NjghIiwiaWF0IjoxNjU3NzAyNDcwLCJleHAiOjE2NTc3MDI0ODV9.DDQKU5mtZtT6bCB9I4ZW32rJImxSqo44R4aHyH0slXo
###
