###
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJOYW1lIjoiR2FsaWggQWRoaSIsInVzZXJfbGluayI6InVzZXIxMDIzIiwiaWF0IjoxNjU3Mjc1MzQxLCJleHAiOjE2NTcyNzUzNTZ9.VpDbPSAIW4SmS2S_5rS-pyyaDOB--K95UdqpfjG3BAM
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username" : "thomas slebew",
    "password" : "123",
    "confirmationPass" : "123",
    "userLink" : "user1010"

}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username" : "Galih Adhi",
    "password" : "123"
}

###
POST http://localhost:3001/api/token

###
DELETE http://localhost:3001/logout
Content-Type: application/json

{
    "username" : "Galih Adhi",
    "password" : "123"
}


###
POST http://localhost:3001/api/send/message/user1023
Content-Type: application/json

{
    "from" : "mamang thomas",
    "to" : "galih san",
    "message": "ayo"
}

###
GET http://localhost:3001/api/get/message/user1023
